source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               plugin.xml,\
               icons/,\
               build.properties
src.excludes = src/
javacSource.. = 11
javacTarget.. = 11
